Joining the Windows Insider Program (#99)
Microsoft-community/Community-website pull request #100
Opened 2021-09-12 03:11 UTC by cleverActon0126

Added a new wiki, this page REQUIRES monthly maintenance to maintain the update. Please feel free to contribute to it.

2021-09-13 00:28 UTC, Erisa commented
>  this page REQUIRES monthly maintenance to maintain the update. 

What do you mean?

2021-09-13 08:53 UTC, cleverActon0126 commented
Just to remind myself to keep it updated. You can ignore that.

2021-09-17 02:55 UTC, goldsolitude commented
Looks okay, some images are not correct for _Leaving the Windows Insider Program_ section however and there are a couple grammatical errors but that can be fixed while its being finalized. The _Error Code_ section in troubleshooting should be moved to the bottom as it doesn't contain much content and looks odd between two filled sections,

2021-09-18 00:44 UTC, cleverActon0126 commented
Alright, I will work on this in a bit. Thanks :D

> Looks okay, some images are not correct for _Leaving the Windows Insider Program_ section however and there are a couple grammatical errors throughout the entire document but that can be fixed while its being finalized. The _Error Code_ section in troubleshooting should be moved to the bottom as it doesn't contain much content and looks odd between two filled sections,

2021-09-19 04:11 UTC, cleverActon0126 commented
Also can you please point out the image that is not correct for leaving? My end is kinda messed up now since I did this so many times.

2021-09-20 05:04 UTC, goldsolitude commented
> Also can you please point out the image that is not correct for leaving? My end is kinda messed up now since I did this so many times.

The get started image in particular, the rest seems fine 
![image](https://user-images.githubusercontent.com/28206096/133958871-098c7f80-6e88-495d-b691-ff3aba880a6c.png)

2021-09-20 09:44 UTC, cleverActon0126 commented
Can you replace the image since this is what I can only get? Thanks.

2021-11-12 12:51 UTC, Erisa commented
@goldsolitude is this okay now?

2021-12-17 21:29 UTC, Erisa requested changes
My changes are
- Change italics to bold for buttons/etc
- Use quotes around longer italicised lines
- Fix some typos
- Clarify that the registry is dangerous
- Other fixes/clarifications

I will commit these suggestions and look at merging later today, have to go now

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +> You must be logged onto a Microsoft Account to be able to join the Windows Insider program. This guide is dedicated to Windows 10 only.
```suggestion
> You must be logged onto a Microsoft Account to be able to join the Windows Insider program.
> This guide is intented to be followed from Windows 10 only, but allows you to receieve Windows 11 builds after joining.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +2. Click on *Windows Insider Program* on the sidebar to navigate to the sign up page.
```suggestion
2. Click on **Windows Insider Program** on the sidebar to navigate to the sign up page.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +1. Open the Settings app. You can do this by searching for it in the Start menu, pressing <kbd>Win</kbd> + <kbd>I</kbd>, or clicking the Settings button found above the Power button in Start. After t
```suggestion
1. Open the Settings app. You can do this by searching for it in the Start menu, pressing <kbd>Win</kbd> + <kbd>I</kbd>, or clicking the Settings button found above the Power button in Start. After that, open the **Update & Security** Section. 
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +3. Click on the *Get Started* button to join the Windows Insider Program.
```suggestion
3. Click on the **Get Started** button to join the Windows Insider Program.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +5. You will be prompted with a pop-up as shown below, click on *Sign Up*.
```suggestion
5. You will be prompted with a pop-up as shown below, click on **Sign Up**.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +6. Read the [Windows Insider Program Agreement](https://insider.windows.com/program-agreement) and the [Microsoft Insider Privacy Agreement](https://privacy.microsoft.com/privacystatement), then chec
```suggestion
6. Read the [Windows Insider Program Agreement](https://insider.windows.com/program-agreement) and the [Microsoft Insider Privacy Agreement](https://privacy.microsoft.com/privacystatement), then check **I've read and accept the terms of this agreement** if you agree. Then click **Submit**.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +8. Now select a channel to receive insider builds, then click *Confirm*. Here are some details on the details of the 3 channels:
```suggestion
8. Now select a channel to receive insider builds, then click **Confirm**. Here are some details on the details of the 3 channels:
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +7. Link an account to join the Windows Insider Program, then click *Continue*.
```suggestion
7. Link an account to join the Windows Insider Program, then click **Continue**.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +9. Read the [Microsoft Insider Privacy Statement](https://privacy.microsoft.com/privacystatement) and the [Microsoft Insider Program Agreement](https://insider.windows.com/program-agreement), then cl
```suggestion
9. Read the [Microsoft Insider Privacy Statement](https://privacy.microsoft.com/privacystatement) and the [Microsoft Insider Program Agreement](https://insider.windows.com/program-agreement), then click **Confirm**.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +A registry might be preventing the page from appearing in settings. Here is what you can do:
```suggestion
A registry key might be preventing the page from appearing in settings. Here is what you can do to fix it:

> Editing the registry incorrectly can cause major problems. Make sure you follow the instructions here exactly and don't proceed if anything is unusual.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +> If the registry does not exists, right click the key *UI* on the side bar and press *New > Key* and name it `Visibility`.
```suggestion
> If the registry key does not exist, right click the key `UI` on the side bar and press **New > Key** and name it `Visibility`.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +You may see an error code as you are trying to register to be a Windows Insider. There are a lot of different error codes, please search up the error code for solutions.
```suggestion
You may see an error code while trying to register to be a Windows Insider. There are a lot of different error codes, so you should search it on the Internet or ask in [our Discord server](https://discord.gg/microsoft) for support (`#insiders` channel).
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +If you see *To manage the Windows Insider programme settings for your device and allow it to stay in the Windows Insider programme, you'll need to turn on optional diagnostic data.*, click on *Go to
```suggestion
If you see *"To manage the Windows Insider programme settings for your device and allow it to stay in the Windows Insider programme, you'll need to turn on optional diagnostic data."*, click on *"Go to Diagnostics & Feedback settings to turn on optional diagnostic data."*. 
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +6. You should see *This email address is not registered as a Windows Insider*. If you don't see it, please redo step 3 and step 4.
```suggestion
6. You should see *"This email address is not registered as a Windows Insider"*. If you don't see it, please redo step 3 and step 4.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +5. Click on *Stop receiving Insider Preview Builds*.
```suggestion
5. Click on **Stop receiving Insider Preview Builds**.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +3. Click on *Leave the Insider Program*.
```suggestion
3. Click on **Leave the Insider Program**.
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +2. Click on *Windows Insider program*
```suggestion
2. Click on **Windows Insider program**
```

2021-12-17 21:29 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +Select *Optional diagnostic data* and return back the the Windows Insider Program page.
```suggestion
Select **Optional diagnostic data** and return back the the Windows Insider Program page.
```

2021-12-17 22:22 UTC, Erisa requested changes
One missing italic -> bold

2021-12-17 22:22 UTC, Erisa commented on wiki/joining-windows-insiders.md
> +4. Click on *Register* to join the Windows Insider Program.
```suggestion
4. Click on **Register** to join the Windows Insider Program.
```

2021-12-17 22:43 UTC, merged