Update Member Docs
Microsoft-community/Community-website pull request #137
Opened 2023-03-06 20:12 UTC by cleverActon0126

2023-05-25 15:47 UTC, heftymouse approved these changes

2023-05-27 19:47 UTC, Erisa requested changes

2023-05-27 19:47 UTC, Erisa commented on member/index.md
> +| #minceraft-server          | Use this channel to discuss our official Minecraft SMP server! Details to join are available in the channel description. Note that it is role-gated to members with the
Torch said no
```suggestion
| #minecraft-server          | Use this channel to discuss our official Minecraft SMP server! Details to join are available in the channel description. Note that it is role-gated to members with the Regular role or higher, Microsoft employees or Nitro boosters.                                    |
```

2023-05-27 19:47 UTC, Erisa commented on member/index.md
> +| #tech-support-forum.       | An experimental replacement for #tech-support using Discord's Forum Channels. Allows for more organised discussion in help threads.
```suggestion
| #tech-support-forum       | An experimental replacement for #tech-support using Discord's Forum Channels. Allows for more organised discussion in help threads.                                                                                                                                       |
```

2023-05-27 19:47 UTC, Erisa commented on member/index.md
> +## Member Information
Why?

2023-05-27 19:50 UTC, waitwhatActo commented on member/index.md
> +## Member Information
might be a typo

2023-05-27 19:50 UTC, Erisa commented on member/index.md
> +## Member Information
```suggestion
# Member Information
```

2023-05-27 19:57 UTC, Erisa approved these changes

2023-05-27 19:57 UTC, merged