Added disabling Bing & automatic File Explorer folder type discovery tips
Microsoft-community/Community-website pull request #168
Opened 2024-06-11 16:00 UTC by itsWindows11

2024-06-19 22:04 UTC, FloatingMilkshake commented
Looks good to me, though I would maybe include a note about backing up the registry—messing with the registry can be dangerous, and it would be helpful to direct people to make a backup before they change anything. That way, if something goes wrong, they can easily roll back.

2024-06-20 09:00 UTC, itsWindows11 commented
Do I include this in each section (i.e. one for disabling Bing and another for FE) or just at the beginning of the article?

2024-06-20 11:02 UTC, sthivaios commented
> Do I include this in each section (i.e. one for disabling Bing and another for FE) or just at the beginning of the article?

Imo it might be better to add a little section on how to do that at the bottom of the page and then add a link in each section that takes you to the registry backup section. You can of course do that with headers.

2024-06-22 02:13 UTC, FloatingMilkshake commented
I don't feel that backing up the registry should be its own section, so I would say a quick mention in each section works. Maybe something along the lines of

> [vuepress note]
> 
> **Important!**
> Before making any changes to the registry, you should take a backup of its current state. You can back up the [folder name] folder by right-clicking it, selecting **Export**, and choosing a safe place like your Desktop to store the backup. If something goes wrong in this section, you can double-click the file on your desktop to undo your changes to that part of the registry.
> 
> [maybe include a screenshot]

2024-06-22 03:40 UTC, sthivaios commented
> I don't feel that backing up the registry should be its own section, so I would say a quick mention in each section works. Maybe something along the lines of
> 
> > [vuepress note]
> > **Important!**
> > Before making any changes to the registry, you should take a backup of its current state. You can back up the [folder name] folder by right-clicking it, selecting **Export**, and choosing a safe place like your Desktop to store the backup. If something goes wrong in this section, you can double-click the file on your desktop to undo your changes to that part of the registry.
> > [maybe include a screenshot]

fair, but i would make it a caution or warning, not a note

2024-06-22 03:44 UTC, FloatingMilkshake commented
> fair, but i would make it a caution or warning, not a note

I agree; by "note" I just meant it would be useful to use one of the fancy vuepress note things—I don't know the proper name for them. Apologies for the lack of clarity. Backups (especially of the registry!) are very important, and they should be stressed here because messing with the registry can be dangerous! I think the 'danger' type with an "IMPORTANT" title or something like that would work. 'Warning' and 'danger' are both probably fine though.

2024-06-22 11:36 UTC, itsWindows11 commented
> I just meant it would be useful to use one of the fancy vuepress note things

Custom containers: https://vitepress.dev/guide/markdown#custom-containers

It also supports expand/collapse details too. There are other markdown extensions listed in that page but no idea whether VitePress supports additional markdown extensions compared to VuePress 2 that we may want to use, anyway probably offtopic for this PR :p

2024-06-25 18:45 UTC, Erisa approved these changes

2024-06-26 11:26 UTC, sthivaios requested changes
Added the "backup the registry first" notes.

2024-06-26 11:26 UTC, sthivaios commented on wiki/useful-windows-tips.md
> +
```suggestion

::: danger Caution
Before making changes to the registry, you should always backup the current state of the folder you are modifying. Right click on the folder you are making the changes to, in the Registry Editor, then click **Export** and save the file somewhere safe. If something goes wrong, you can restore the backup by double-clicking on the file. You can also go to **File > Import**, in the Registry Editor.
:::

```

2024-06-26 11:26 UTC, sthivaios commented on wiki/useful-windows-tips.md
> +
```suggestion

::: danger Caution
Before making changes to the registry, you should always backup the current state of the folder you are modifying. Right click on the folder you are making the changes to, in the Registry Editor, then click **Export** and save the file somewhere safe. If something goes wrong, you can restore the backup by double-clicking on the file. You can also go to **File > Import**, in the Registry Editor.
:::

```

2024-06-26 11:57 UTC, itsWindows11 commented
PR should be ready to merge now, assuming there are no more changes to be requested.

2024-06-26 11:58 UTC, Erisa approved these changes
Still lgtm

2024-06-26 11:59 UTC, merged