Vanity link clarification plus some trivial cosmetic fixes on the Keyboard Shortcuts page
Microsoft-community/Community-website pull request #186
Opened 2024-08-19 18:18 UTC by aervnu

Flat out long list is still readable to some degree, but a collapsible is preferred. Would love it if someone can test the deployments out though

2024-08-19 18:56 UTC, itsWindows11 commented
Expand/collapse functionality doesn't seem to be working at all.

I had a better idea for this section, basically put each server and a brief description in a card, in a way that's consistent with the way VitePress features look in the home page.

You can deploy the site locally or test your changes by clicking on "Details" for the `deploy/netlify` test.

2024-08-19 18:59 UTC, itsWindows11 commented
Or simply use the details custom container, it has expand/collapse & you can set a custom title like any custom container used in the site.

https://vitepress.dev/guide/markdown#default-title

2024-08-19 19:05 UTC, aervnu commented
> Or simply use the details custom container, it has expand/collapse & you can set a custom title like any custom container used in the site.
> 
> https://vitepress.dev/guide/markdown#custom-title

Yeah this seems to be the quickest and cleanest way. I'll deal with that, just a sec

2024-08-19 19:22 UTC, itsWindows11 requested changes

2024-08-19 19:22 UTC, itsWindows11 commented on src/mod/docs/index.md
> +::: details Approved vanity links
```suggestion
::: details Approved Vanity Links
```

2024-08-19 19:22 UTC, itsWindows11 commented on src/mod/docs/index.md
> +:::
```suggestion
::: tip Note
Action will only be taken when unapproved invites are being sent. Certain approved invite links can be sent by any member regardless of their role, provided that they are not muted.
:::
```

2024-08-23 08:26 UTC, aervnu commented
My bad. I just resumed work on my new PC and while trying to sync all local repos to origin I accidentally clicked delete branch without realizing this PR is still open and hasn't been merged yet. Apologies.

2024-08-26 01:02 UTC, aervnu commented
Fixed that. Would make the note less apparent though, since the text is now on a gray background instead of blue like the Tip container. But I do agree on the "see below" note - that one definitely needs to be relocated.

2024-08-26 02:11 UTC, FloatingMilkshake commented
> Would make the note less apparent though, since the text is now on a gray background instead of blue like the Tip container

Honestly, my first thought was to shove the entire custom container into the collapsible, if possible—but I think I like the look of this. While the note doesn't draw as much attention, I think it's still probably prominent enough. So either way is okay with me!

Thanks!

2024-08-26 02:11 UTC, FloatingMilkshake approved these changes

2024-08-26 13:23 UTC, merged