Adding alt text and fixing a ton of (I mean it) markdown formatting issues
Microsoft-community/Community-website pull request #193
Opened 2024-09-16 15:10 UTC by aervnu

Originally this was to only add alt text, but I found out that markdownlint was reporting multiple formatting issues, so I tried to fix as many of them as possible. I left some ordered lists and inline HTMLs intact (such as tags) since I don't know how to deal with these without making the code look even messier.

I understand the potential of this breaking formatting on some (if not all) pages plus GitHub-related issues, so I welcome all constructive feedback.

2024-09-16 15:15 UTC, aervnu commented
Seems like I reused the commits from an older PR, pretty sure I forgot to sync my repo with the original one. I mean, it's not clean for code maintainers so I can make another entirely new one ig.

2024-09-16 17:09 UTC, itsWindows11 commented
Rebase the PR branch from upstream `master` branch then re-implement your changes.

2024-09-16 17:14 UTC, itsWindows11 commented on src/wiki/windows-insiders.md
> +![More agreements smh](./img/windows-insider/11/agreement-2.png)
```suggestion
![More agreements](./img/windows-insider/11/agreement-2.png)
```

2024-09-16 17:15 UTC, itsWindows11 commented on src/wiki/windows-insiders.md
> +![Agreements again](./img/windows-insider/10/agreement.png)
```suggestion
![Agreements](./img/windows-insider/10/agreement.png)
```

2024-09-16 17:17 UTC, itsWindows11 commented on src/wiki/windows-insiders.md
> +![Really leaving](./img/windows-insider/10/leaving-the-program.png)
Please use more descriptive alts. "Really leaving" isn't really descriptive for users that rely on screenreaders.

2024-09-16 17:17 UTC, itsWindows11 requested changes
a

2024-09-19 14:43 UTC, FloatingMilkshake commented
Please make sure that alt text is descriptive. One- or two-word descriptions usually aren't descriptive enough.

2024-09-19 14:49 UTC, FloatingMilkshake approved these changes

2024-09-19 17:47 UTC, aervnu commented
Really didn't expect you to add them yourself. I appreciate the effort and will remember to utilize alt text more responsibly in the future. I think you're free to merge the PR now, and thanks again for all those fixes!

2024-09-19 18:00 UTC, Erisa approved these changes

2024-09-19 18:00 UTC, merged