Try to clean up the installing-and-updating-drivers flow
Microsoft-community/Community-website pull request #195
Opened 2024-09-19 18:10 UTC by Erisa

2024-09-19 18:21 UTC, FloatingMilkshake approved these changes

2024-09-19 18:31 UTC, FloatingMilkshake requested changes

2024-09-19 18:31 UTC, FloatingMilkshake commented on src/wiki/installing-and-updating-drivers.md
```suggestion
```
Guessing the 4 was added by mistake

2024-09-19 18:34 UTC, FloatingMilkshake approved these changes

2024-09-19 18:35 UTC, julsehn commented
wait a sec

2024-09-19 19:22 UTC, julsehn requested changes
Page direction wrong

2024-09-20 06:50 UTC, itsWindows11 commented
What's wrong with the page "direction"?

2024-09-20 10:46 UTC, julsehn commented
> What's wrong with the page "direction"?

Page direction at the last line in the file.

2024-09-20 11:01 UTC, merged